"""Domain models: ORM tables, Pydantic schemas, shared enums."""

from model.enums import (
    AgentType,
    BillingCycle,
    CommentSeverity,
    MemberRole,
    ReviewFileStatus,
    ReviewStatus,
    SubscriptionStatus,
    TriggeredBy,
)
from model.schemas import (
    Agent,
    GitHubEvent,
    GitHubInstallation,
    Model,
    Organization,
    OrganizationMember,
    OrganizationModelKey,
    PullRequest,
    Repository,
    RepositoryAgent,
    ReviewComment,
    ReviewFile,
    ReviewRun,
    Subscription,
    SubscriptionAgent,
    TokenUsage,
    User,
)
from model.tables import (
    Agent as AgentTable,
    CoderWorkflowUsage as CoderWorkflowUsageTable,
    GitHubEvent as GitHubEventTable,
    GitHubInstallation as GitHubInstallationTable,
    Model as ModelTable,
    Organization as OrganizationTable,
    OrganizationMember as OrganizationMemberTable,
    OrganizationModelKey as OrganizationModelKeyTable,
    PullRequest as PullRequestTable,
    Repository as RepositoryTable,
    RepositoryAgent as RepositoryAgentTable,
    ReviewComment as ReviewCommentTable,
    ReviewFile as ReviewFileTable,
    ReviewRun as ReviewRunTable,
    Subscription as SubscriptionTable,
    SubscriptionAgent as SubscriptionAgentTable,
    TokenUsage as TokenUsageTable,
    User as UserTable,
)

__all__ = [
    # Enums
    "AgentType",
    "BillingCycle",
    "CommentSeverity",
    "MemberRole",
    "ReviewFileStatus",
    "ReviewStatus",
    "SubscriptionStatus",
    "TriggeredBy",
    # Schemas
    "Agent",
    "GitHubEvent",
    "GitHubInstallation",
    "Model",
    "Organization",
    "OrganizationMember",
    "OrganizationModelKey",
    "PullRequest",
    "Repository",
    "RepositoryAgent",
    "ReviewComment",
    "ReviewFile",
    "ReviewRun",
    "Subscription",
    "SubscriptionAgent",
    "TokenUsage",
    "User",
    # Tables (aliased to avoid collision with schema names)
    "AgentTable",
    "CoderWorkflowUsageTable",
    "GitHubEventTable",
    "GitHubInstallationTable",
    "ModelTable",
    "OrganizationTable",
    "OrganizationMemberTable",
    "OrganizationModelKeyTable",
    "PullRequestTable",
    "RepositoryTable",
    "RepositoryAgentTable",
    "ReviewCommentTable",
    "ReviewFileTable",
    "ReviewRunTable",
    "SubscriptionTable",
    "SubscriptionAgentTable",
    "TokenUsageTable",
    "UserTable",
]
